import numpy as np 
a=np.array([10,20,30,40,50])
b=np.array([5,4,3,2,1])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.mean())
print(a.min())
print(a.max())
dot_product=np.dot(a,b)
print("dot product of a and b:",dot_product)
x=a.reshape(5,1)
print(x)